name: CI

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    run-test:
        strategy:
            matrix:
                python-version: ["3.10", "3.11"]
                os: [ubuntu-latest]
            fail-fast: false
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  python -m pip install -e .[tests]

            - name: Checks with pre-commit
              uses: pre-commit/action@v2.0.3

            - name: Test with pytest
              run: pytest -n auto -- mission_control/_src/

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
